### ISSUE TITLE
TypeScript files are not getting generated for entity models correctly

### ISSUE THREAD

**Issue by manojadams** [telosys-templates-v3/angular4-rest-frontend#1]
Hi author,

I am currently using this templates for generation of angular files (from eclipse oxygen ) from entity models (generated though telosys tools) but I found an issue while trying to generate the typescript files (Entity.service.ts and Entity.form.component.ts) of the entities.

It gives the following exception:

Exception: 'GeneratorEngineException';
Generator engine error: ResourceNotFoundException

ResourceNotFoundException:
Unable to find resource '../../../../include/entitiesNamesRef.vm'

Solution: I am also pleased to inform that I have been able to resolve the issue by just editing the template files and change #parse("../../../../include/entitiesNamesRef.vm") to #parse("include/entitiesNamesRef.vm")

Would request you to make the changes to the repository.

Thank you,
Manoj Baruah

**Comment by l-gu** [comment]
Thank you for this information.
Problem fixed.
